/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package model;
import model.ZeroOneGenerator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ZeroOneGeneratorTest {
    
    private ZeroOneGenerator zog;
    
    public ZeroOneGeneratorTest(){
        zog = new ZeroOneGenerator();
    }
    @Test 
    public void testA() {
        System.out.println(zog.getZeroOrOne());
        assertEquals(1, zog.getZeroOrOne());
        
    }
    
    @Test
    public void testB() {
        System.out.println(zog.getZeroOrOne());
        assertEquals(1, zog.getZeroOrOne());
    }
    
    @Test
    public void testC() {
        System.out.println(zog.getZeroOrOne());
        assertEquals(1, zog.getZeroOrOne());
    }   
}
