/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package model;
import model.ZeroOneGenerator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;
import org.junit.jupiter.api.MethodOrderer.Alphanumeric;
import org.junit.jupiter.api.TestMethodOrder;

@TestMethodOrder(Alphanumeric.class)
@TestInstance(Lifecycle.PER_CLASS)
public class ZeroOneGeneratorTestOneObject {
    
    private ZeroOneGenerator zog;
    
    public ZeroOneGeneratorTestOneObject(){
        zog = new ZeroOneGenerator();
    }
    
    @Test 
    public void testZ() {
        System.out.println(zog.getZeroOrOne());
        assertEquals(1, zog.getZeroOrOne());
        
    }
    @Test 
    public void testA() {
        System.out.println(zog.getZeroOrOne());
        assertEquals(1, zog.getZeroOrOne());
        
    }
    
    @Test
    public void testB() {
        System.out.println(zog.getZeroOrOne());
        assertEquals(1, zog.getZeroOrOne());
    }
    
    @Test
    public void testC() {
        System.out.println(zog.getZeroOrOne());
        assertEquals(1, zog.getZeroOrOne());
    }   
}
